language: go

services: docker

before_script:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh

jobs:
  include:
    - stage: "Test the code build"
      script:
      - sh build.sh
      - ./dist/TechTestApp --help
    - stage: "Build docker image"
      script:
      - docker build . -t techtestapp:latest
      - docker images