language: go

services:
  - docker

before_script:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - sudo curl -o /usr/local/bin/ecs-cli https://amazon-ecs-cli.s3.amazonaws.com/ecs-cli-linux-amd64-latest
  - sudo chmod +x /usr/local/bin/ecs-cli

jobs:
  include:
    - stage: "Test the code build"
      script:
      - sh build.sh
      - ./dist/TechTestApp --help
    - stage: "Build and push docker image"
      script:
      - docker build . -t techtestapp:latest
      - docker images
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker tag techtestapp:latest "$DOCKER_USERNAME/techtestapp"
      - docker push "$DOCKER_USERNAME/techtestapp"
    - stage: "Deploy to AWS ECS"
      script:
        - ecs-cli configure profile --profile-name techtestapp_profile --access-key "$AWS_ACCESS_KEY" --secret-key "$AWS_SECRET_KEY"
        - ecs-cli configure --cluster techtestapp --region us-west-2
        - ecs-cli up --capability-iam
        - ecs-cli compose --file docker-compose.yml up
