version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"

  web:
    links:
      - db:postgres
    image: techtestapp:latest
    ports:
      - "3000:3000"
