version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changeme
    ports:
      - "5432:5432"
    networks:
      - testappnetwork

  web:
    links:
      - db:postgres
    image: abybhamra/techtestapp:latest
    ports:
      - "80:3000"
    networks:
      - testappnetwork

networks:
  testappnetwork:
    driver: bridge