version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - testappnetwork
    environment:
      POSTGRES_USER: ${VTT_DBUSER}
      POSTGRES_PASSWORD: ${VTT_DBPASSWORD}
  web:
    links:
      - db:postgres
    image: abybhamra/techtestapp:latest
    ports:
      - "80:3000"
    networks:
      - testappnetwork
    environment:
      VTT_DBNAME: ${VTT_DBNAME}
      VTT_DBUSER: ${VTT_DBUSER}
      VTT_DBPASSWORD: ${VTT_DBPASSWORD}
volumes:
  database-data:

networks:
  testappnetwork:
    driver: bridge